### ISSUE TITLE
No module named 'config'

### ISSUE THREAD

**Issue by ryu2gaku** [MoeOverflow/hentaibook#3]
Traceback (most recent call last):
  File "comicbook.py", line 6, in <module>
    from crawler.__init__ import Crawler
  File "/Users/ryugaku/PycharmProjects/comicbook/crawler/__init__.py", line 5, in <module>
    import config
ModuleNotFoundError: No module named 'config'

**Comment by shincurry** [comment]
```
cp config.example.py config.py
vim config.py
```

...
